"""
Maestro oficial de comunas, ciudades y regiones de Chile.
Generado desde el Excel "comunas_chile.xlsx" proporcionado por el cliente.
"""

# Regiones: código (2 dígitos) → nombre
REGIONES = {
    "01": "Tarapacá",
    "02": "Antofagasta",
    "03": "Atacama",
    "04": "Coquimbo",
    "05": "Valparaíso",
    "06": "Libertador General Bernardo O'Higgins",
    "07": "Maule",
    "08": "Biobío",
    "09": "La Araucanía",
    "10": "Los Lagos",
    "11": "Aysén del General Carlos Ibáñez del Campo",
    "12": "Magallanes y de la Antártica Chilena",
    "13": "Metropolitana de Santiago",
    "14": "Los Ríos",
    "15": "Arica y Parinacota",
    "16": "Ñuble",
}

# Comunas: código → {nombre, cod_ciudad, nom_ciudad, cod_region, nom_region}
COMUNAS = {
    "15102": {
        "nombre":     "Camarones",
        "cod_ciudad": "Camarones",
        "nom_ciudad": "Caleta Camarones",
        "cod_region": "15",
        "nom_region": "Arica y Parinacota",
    },
    "15201": {
        "nombre":     "Putre",
        "cod_ciudad": "Putre",
        "nom_ciudad": "Putre",
        "cod_region": "15",
        "nom_region": "Arica y Parinacota",
    },
    "15202": {
        "nombre":     "General Lagos",
        "cod_ciudad": "GeneralLagos",
        "nom_ciudad": "General Lagos",
        "cod_region": "15",
        "nom_region": "Arica y Parinacota",
    },
    "01101": {
        "nombre":     "Iquique",
        "cod_ciudad": "Iquique",
        "nom_ciudad": "Iquique",
        "cod_region": "01",
        "nom_region": "Tarapacá",
    },
    "01402": {
        "nombre":     "Camiña",
        "cod_ciudad": "Camiña",
        "nom_ciudad": "Camiña",
        "cod_region": "01",
        "nom_region": "Tarapacá",
    },
    "01403": {
        "nombre":     "Colchane",
        "cod_ciudad": "Colchane",
        "nom_ciudad": "Colchane",
        "cod_region": "01",
        "nom_region": "Tarapacá",
    },
    "01404": {
        "nombre":     "Huara",
        "cod_ciudad": "Huara",
        "nom_ciudad": "Huara",
        "cod_region": "01",
        "nom_region": "Tarapacá",
    },
    "01405": {
        "nombre":     "Pica",
        "cod_ciudad": "Pica",
        "nom_ciudad": "Pica",
        "cod_region": "01",
        "nom_region": "Tarapacá",
    },
    "01401": {
        "nombre":     "Pozo Almonte",
        "cod_ciudad": "PozoAlmonte",
        "nom_ciudad": "Pozo Almonte",
        "cod_region": "01",
        "nom_region": "Tarapacá",
    },
    "01107": {
        "nombre":     "Alto Hospicio",
        "cod_ciudad": "AltoHospicio",
        "nom_ciudad": "Alto Hospicio",
        "cod_region": "01",
        "nom_region": "Tarapacá",
    },
    "02101": {
        "nombre":     "Antofagasta",
        "cod_ciudad": "Antofagasta",
        "nom_ciudad": "Antofagasta",
        "cod_region": "02",
        "nom_region": "Antofagasta",
    },
    "02102": {
        "nombre":     "Mejillones",
        "cod_ciudad": "Mejillones",
        "nom_ciudad": "Mejillones",
        "cod_region": "02",
        "nom_region": "Antofagasta",
    },
    "02103": {
        "nombre":     "Sierra Gorda",
        "cod_ciudad": "SierraGorda",
        "nom_ciudad": "Sierra Gorda",
        "cod_region": "02",
        "nom_region": "Antofagasta",
    },
    "02104": {
        "nombre":     "Taltal",
        "cod_ciudad": "TalTal",
        "nom_ciudad": "Tal-Tal",
        "cod_region": "02",
        "nom_region": "Antofagasta",
    },
    "02302": {
        "nombre":     "Maria Elena",
        "cod_ciudad": "MariaElena",
        "nom_ciudad": "Maria Elena",
        "cod_region": "02",
        "nom_region": "Antofagasta",
    },
    "02201": {
        "nombre":     "Calama",
        "cod_ciudad": "Calama",
        "nom_ciudad": "Calama",
        "cod_region": "02",
        "nom_region": "Antofagasta",
    },
    "02202": {
        "nombre":     "Ollague",
        "cod_ciudad": "Ollague",
        "nom_ciudad": "Ollague",
        "cod_region": "02",
        "nom_region": "Antofagasta",
    },
    "02203": {
        "nombre":     "San Pedro De Atacama",
        "cod_ciudad": "SanPedroAtacama",
        "nom_ciudad": "San Pedro Atacama",
        "cod_region": "02",
        "nom_region": "Antofagasta",
    },
    "02301": {
        "nombre":     "Tocopilla",
        "cod_ciudad": "Tocopilla",
        "nom_ciudad": "Tocopilla",
        "cod_region": "02",
        "nom_region": "Antofagasta",
    },
    "03101": {
        "nombre":     "Copiapo",
        "cod_ciudad": "Copiapo",
        "nom_ciudad": "Copiapo",
        "cod_region": "03",
        "nom_region": "Atacama",
    },
    "03102": {
        "nombre":     "Caldera",
        "cod_ciudad": "Caldera",
        "nom_ciudad": "Caldera",
        "cod_region": "03",
        "nom_region": "Atacama",
    },
    "03103": {
        "nombre":     "Tierra Amarilla",
        "cod_ciudad": "TierraAmarilla",
        "nom_ciudad": "Tierra Amarilla",
        "cod_region": "03",
        "nom_region": "Atacama",
    },
    "03201": {
        "nombre":     "Chañaral",
        "cod_ciudad": "Chañaral",
        "nom_ciudad": "Chañaral",
        "cod_region": "03",
        "nom_region": "Atacama",
    },
    "03202": {
        "nombre":     "Diego De Almagro",
        "cod_ciudad": "DiegoDeAlmagro",
        "nom_ciudad": "Diego De Almagro",
        "cod_region": "03",
        "nom_region": "Atacama",
    },
    "03301": {
        "nombre":     "Vallenar",
        "cod_ciudad": "Vallenar",
        "nom_ciudad": "Vallenar",
        "cod_region": "03",
        "nom_region": "Atacama",
    },
    "03302": {
        "nombre":     "Alto Del Carmen",
        "cod_ciudad": "AltoDelCarmen",
        "nom_ciudad": "Alto Del Carmen",
        "cod_region": "03",
        "nom_region": "Atacama",
    },
    "03303": {
        "nombre":     "Freirina",
        "cod_ciudad": "Freirina",
        "nom_ciudad": "Freirina",
        "cod_region": "03",
        "nom_region": "Atacama",
    },
    "03304": {
        "nombre":     "Huasco",
        "cod_ciudad": "Huasco",
        "nom_ciudad": "Huasco",
        "cod_region": "03",
        "nom_region": "Atacama",
    },
    "04101": {
        "nombre":     "La Serena",
        "cod_ciudad": "LaSerena",
        "nom_ciudad": "La Serena",
        "cod_region": "04",
        "nom_region": "Coquimbo",
    },
    "04102": {
        "nombre":     "Coquimbo",
        "cod_ciudad": "Coquimbo",
        "nom_ciudad": "Coquimbo",
        "cod_region": "04",
        "nom_region": "Coquimbo",
    },
    "04103": {
        "nombre":     "Andacollo",
        "cod_ciudad": "Andacollo",
        "nom_ciudad": "Andacollo",
        "cod_region": "04",
        "nom_region": "Coquimbo",
    },
    "04104": {
        "nombre":     "La Higuera",
        "cod_ciudad": "Higueras",
        "nom_ciudad": "Higueras",
        "cod_region": "04",
        "nom_region": "Coquimbo",
    },
    "04105": {
        "nombre":     "Paiguano",
        "cod_ciudad": "Paiguano",
        "nom_ciudad": "Paiguano",
        "cod_region": "04",
        "nom_region": "Coquimbo",
    },
    "04106": {
        "nombre":     "Vicuña",
        "cod_ciudad": "Vicuna",
        "nom_ciudad": "Vicuña",
        "cod_region": "04",
        "nom_region": "Coquimbo",
    },
    "04201": {
        "nombre":     "Illapel",
        "cod_ciudad": "Illapel",
        "nom_ciudad": "Illapel",
        "cod_region": "04",
        "nom_region": "Coquimbo",
    },
    "04202": {
        "nombre":     "Canela",
        "cod_ciudad": "Canela",
        "nom_ciudad": "Canela",
        "cod_region": "04",
        "nom_region": "Coquimbo",
    },
    "04203": {
        "nombre":     "Los Vilos",
        "cod_ciudad": "LosVilos",
        "nom_ciudad": "Los Vilos",
        "cod_region": "04",
        "nom_region": "Coquimbo",
    },
    "04204": {
        "nombre":     "Salamanca",
        "cod_ciudad": "Salamanca",
        "nom_ciudad": "Salamanca",
        "cod_region": "04",
        "nom_region": "Coquimbo",
    },
    "04301": {
        "nombre":     "Ovalle",
        "cod_ciudad": "Ovalle",
        "nom_ciudad": "Ovalle",
        "cod_region": "04",
        "nom_region": "Coquimbo",
    },
    "04302": {
        "nombre":     "Combarbala",
        "cod_ciudad": "Combarbalá",
        "nom_ciudad": "Combarbalá",
        "cod_region": "04",
        "nom_region": "Coquimbo",
    },
    "04303": {
        "nombre":     "Monte Patria",
        "cod_ciudad": "MontePatria",
        "nom_ciudad": "Monte Patria",
        "cod_region": "04",
        "nom_region": "Coquimbo",
    },
    "04304": {
        "nombre":     "Punitaqui",
        "cod_ciudad": "Punitaqui",
        "nom_ciudad": "Punitaqui",
        "cod_region": "04",
        "nom_region": "Coquimbo",
    },
    "04305": {
        "nombre":     "Rio Hurtado",
        "cod_ciudad": "RioHurtado",
        "nom_ciudad": "Río Hurtado",
        "cod_region": "04",
        "nom_region": "Coquimbo",
    },
    "05101": {
        "nombre":     "Valparaiso",
        "cod_ciudad": "Valparaiso",
        "nom_ciudad": "Valparaiso",
        "cod_region": "05",
        "nom_region": "Valparaíso",
    },
    "05102": {
        "nombre":     "Casablanca",
        "cod_ciudad": "Casablanca",
        "nom_ciudad": "Casablanca",
        "cod_region": "05",
        "nom_region": "Valparaíso",
    },
    "05103": {
        "nombre":     "Concon",
        "cod_ciudad": "Concon",
        "nom_ciudad": "Concon",
        "cod_region": "05",
        "nom_region": "Valparaíso",
    },
    "05104": {
        "nombre":     "Juan Fernandez",
        "cod_ciudad": "JuanFernandez",
        "nom_ciudad": "Juan Fernandez",
        "cod_region": "05",
        "nom_region": "Valparaíso",
    },
    "05105": {
        "nombre":     "Puchuncavi",
        "cod_ciudad": "puchuncavi",
        "nom_ciudad": "Puchuncavi",
        "cod_region": "05",
        "nom_region": "Valparaíso",
    },
    "05801": {
        "nombre":     "Quilpue",
        "cod_ciudad": "Quilpue",
        "nom_ciudad": "Quilpue",
        "cod_region": "05",
        "nom_region": "Valparaíso",
    },
    "05107": {
        "nombre":     "Quintero",
        "cod_ciudad": "Quintero",
        "nom_ciudad": "Quintero",
        "cod_region": "05",
        "nom_region": "Valparaíso",
    },
    "05804": {
        "nombre":     "Villa Alemana",
        "cod_ciudad": "VillaAlemana",
        "nom_ciudad": "Villa Alemana",
        "cod_region": "05",
        "nom_region": "Valparaíso",
    },
    "05109": {
        "nombre":     "Viña Del Mar",
        "cod_ciudad": "VinaDelMar",
        "nom_ciudad": "Viña Del Mar",
        "cod_region": "05",
        "nom_region": "Valparaíso",
    },
    "05201": {
        "nombre":     "Isla De Pascua",
        "cod_ciudad": "IslaDePascua",
        "nom_ciudad": "Isla De Pascua",
        "cod_region": "05",
        "nom_region": "Valparaíso",
    },
    "05301": {
        "nombre":     "Los Andes",
        "cod_ciudad": "LosAndes",
        "nom_ciudad": "Los Andes",
        "cod_region": "05",
        "nom_region": "Valparaíso",
    },
    "05302": {
        "nombre":     "Calle Larga",
        "cod_ciudad": "CalleLarga",
        "nom_ciudad": "Calle Larga",
        "cod_region": "05",
        "nom_region": "Valparaíso",
    },
    "05303": {
        "nombre":     "Rinconada",
        "cod_ciudad": "Rinconada",
        "nom_ciudad": "Rinconada",
        "cod_region": "05",
        "nom_region": "Valparaíso",
    },
    "05304": {
        "nombre":     "San Esteban",
        "cod_ciudad": "SanEsteban",
        "nom_ciudad": "San Esteban",
        "cod_region": "05",
        "nom_region": "Valparaíso",
    },
    "05401": {
        "nombre":     "La Ligua",
        "cod_ciudad": "LaLigua",
        "nom_ciudad": "La Ligua",
        "cod_region": "05",
        "nom_region": "Valparaíso",
    },
    "05402": {
        "nombre":     "Cabildo",
        "cod_ciudad": "Cabildo",
        "nom_ciudad": "Cabildo",
        "cod_region": "05",
        "nom_region": "Valparaíso",
    },
    "05403": {
        "nombre":     "Papudo",
        "cod_ciudad": "Papudo",
        "nom_ciudad": "Papudo",
        "cod_region": "05",
        "nom_region": "Valparaíso",
    },
    "05404": {
        "nombre":     "Petorca",
        "cod_ciudad": "Petorca",
        "nom_ciudad": "Petorca",
        "cod_region": "05",
        "nom_region": "Valparaíso",
    },
    "05405": {
        "nombre":     "Zapallar",
        "cod_ciudad": "zapallar",
        "nom_ciudad": "Zapallar",
        "cod_region": "05",
        "nom_region": "Valparaíso",
    },
    "05501": {
        "nombre":     "Quillota",
        "cod_ciudad": "Quillota",
        "nom_ciudad": "Quillota",
        "cod_region": "05",
        "nom_region": "Valparaíso",
    },
    "05502": {
        "nombre":     "Calera",
        "cod_ciudad": "LaCalera",
        "nom_ciudad": "La Calera",
        "cod_region": "05",
        "nom_region": "Valparaíso",
    },
    "05503": {
        "nombre":     "Hijuelas",
        "cod_ciudad": "Hijuelas",
        "nom_ciudad": "Hijuelas",
        "cod_region": "05",
        "nom_region": "Valparaíso",
    },
    "05504": {
        "nombre":     "La Cruz",
        "cod_ciudad": "lacruz",
        "nom_ciudad": "La Cruz",
        "cod_region": "05",
        "nom_region": "Valparaíso",
    },
    "05802": {
        "nombre":     "Limache",
        "cod_ciudad": "Limache",
        "nom_ciudad": "Limache",
        "cod_region": "05",
        "nom_region": "Valparaíso",
    },
    "05506": {
        "nombre":     "Nogales",
        "cod_ciudad": "Nogales",
        "nom_ciudad": "Nogales",
        "cod_region": "05",
        "nom_region": "Valparaíso",
    },
    "05803": {
        "nombre":     "Olmue",
        "cod_ciudad": "Olmue",
        "nom_ciudad": "Olmue",
        "cod_region": "05",
        "nom_region": "Valparaíso",
    },
    "05601": {
        "nombre":     "San Antonio",
        "cod_ciudad": "SanAntonio",
        "nom_ciudad": "San Antonio",
        "cod_region": "05",
        "nom_region": "Valparaíso",
    },
    "05602": {
        "nombre":     "Algarrobo",
        "cod_ciudad": "Algarrobo",
        "nom_ciudad": "Algarrobo",
        "cod_region": "05",
        "nom_region": "Valparaíso",
    },
    "05603": {
        "nombre":     "Cartagena",
        "cod_ciudad": "cartagena",
        "nom_ciudad": "Cartagena",
        "cod_region": "05",
        "nom_region": "Valparaíso",
    },
    "05604": {
        "nombre":     "El Quisco",
        "cod_ciudad": "ElQuisco",
        "nom_ciudad": "El Quisco",
        "cod_region": "05",
        "nom_region": "Valparaíso",
    },
    "05605": {
        "nombre":     "El Tabo",
        "cod_ciudad": "eltabo",
        "nom_ciudad": "El Tabo",
        "cod_region": "05",
        "nom_region": "Valparaíso",
    },
    "05606": {
        "nombre":     "Santo Domingo",
        "cod_ciudad": "SantoDomingo",
        "nom_ciudad": "Santo Domingo",
        "cod_region": "05",
        "nom_region": "Valparaíso",
    },
    "05701": {
        "nombre":     "San Felipe",
        "cod_ciudad": "SanFelipe",
        "nom_ciudad": "San Felipe",
        "cod_region": "05",
        "nom_region": "Valparaíso",
    },
    "05702": {
        "nombre":     "Catemu",
        "cod_ciudad": "Catemu",
        "nom_ciudad": "Catemu",
        "cod_region": "05",
        "nom_region": "Valparaíso",
    },
    "05703": {
        "nombre":     "Llaillay",
        "cod_ciudad": "Llaillay",
        "nom_ciudad": "Llaillay",
        "cod_region": "05",
        "nom_region": "Valparaíso",
    },
    "05704": {
        "nombre":     "Panquehue",
        "cod_ciudad": "Panquehue",
        "nom_ciudad": "Panquehue",
        "cod_region": "05",
        "nom_region": "Valparaíso",
    },
    "05705": {
        "nombre":     "Putaendo",
        "cod_ciudad": "Putaendo",
        "nom_ciudad": "Putaendo",
        "cod_region": "05",
        "nom_region": "Valparaíso",
    },
    "05706": {
        "nombre":     "Santa Maria",
        "cod_ciudad": "SantaMaria",
        "nom_ciudad": "Santa Maria",
        "cod_region": "05",
        "nom_region": "Valparaíso",
    },
    "06101": {
        "nombre":     "Rancagua",
        "cod_ciudad": "Rancagua",
        "nom_ciudad": "Rancagua",
        "cod_region": "06",
        "nom_region": "Libertador General Bernardo O'Higgins",
    },
    "06102": {
        "nombre":     "Codegua",
        "cod_ciudad": "Codegua",
        "nom_ciudad": "Codegua",
        "cod_region": "06",
        "nom_region": "Libertador General Bernardo O'Higgins",
    },
    "06103": {
        "nombre":     "Coinco",
        "cod_ciudad": "coinco",
        "nom_ciudad": "Coinco",
        "cod_region": "06",
        "nom_region": "Libertador General Bernardo O'Higgins",
    },
    "06104": {
        "nombre":     "Coltauco",
        "cod_ciudad": "Coltauco",
        "nom_ciudad": "Coltauco",
        "cod_region": "06",
        "nom_region": "Libertador General Bernardo O'Higgins",
    },
    "06105": {
        "nombre":     "Doñihue",
        "cod_ciudad": "Doñihue",
        "nom_ciudad": "Doñihue",
        "cod_region": "06",
        "nom_region": "Libertador General Bernardo O'Higgins",
    },
    "06106": {
        "nombre":     "Graneros",
        "cod_ciudad": "Graneros",
        "nom_ciudad": "Graneros",
        "cod_region": "06",
        "nom_region": "Libertador General Bernardo O'Higgins",
    },
    "06107": {
        "nombre":     "Las Cabras",
        "cod_ciudad": "LasCabras",
        "nom_ciudad": "Las Cabras",
        "cod_region": "06",
        "nom_region": "Libertador General Bernardo O'Higgins",
    },
    "06108": {
        "nombre":     "Machali",
        "cod_ciudad": "Machali",
        "nom_ciudad": "Machali",
        "cod_region": "06",
        "nom_region": "Libertador General Bernardo O'Higgins",
    },
    "06109": {
        "nombre":     "Malloa",
        "cod_ciudad": "malloa",
        "nom_ciudad": "Malloa",
        "cod_region": "06",
        "nom_region": "Libertador General Bernardo O'Higgins",
    },
    "06110": {
        "nombre":     "Mostazal",
        "cod_ciudad": "SanFranciscoDeMos",
        "nom_ciudad": "San Francisco De Mostazal",
        "cod_region": "06",
        "nom_region": "Libertador General Bernardo O'Higgins",
    },
    "06111": {
        "nombre":     "Olivar",
        "cod_ciudad": "olivar",
        "nom_ciudad": "Olivar",
        "cod_region": "06",
        "nom_region": "Libertador General Bernardo O'Higgins",
    },
    "06112": {
        "nombre":     "Peumo",
        "cod_ciudad": "Peumo",
        "nom_ciudad": "Peumo",
        "cod_region": "06",
        "nom_region": "Libertador General Bernardo O'Higgins",
    },
    "06113": {
        "nombre":     "Pichidegua",
        "cod_ciudad": "Pichidegua",
        "nom_ciudad": "Pichidegua",
        "cod_region": "06",
        "nom_region": "Libertador General Bernardo O'Higgins",
    },
    "06114": {
        "nombre":     "Quinta De Tilcoco",
        "cod_ciudad": "quintadetilcoco",
        "nom_ciudad": "Quinta de Tilcoco",
        "cod_region": "06",
        "nom_region": "Libertador General Bernardo O'Higgins",
    },
    "06115": {
        "nombre":     "Rengo",
        "cod_ciudad": "Rengo",
        "nom_ciudad": "Rengo",
        "cod_region": "06",
        "nom_region": "Libertador General Bernardo O'Higgins",
    },
    "06116": {
        "nombre":     "Requinoa",
        "cod_ciudad": "Requinoa",
        "nom_ciudad": "Requinoa",
        "cod_region": "06",
        "nom_region": "Libertador General Bernardo O'Higgins",
    },
    "06117": {
        "nombre":     "San Vicente",
        "cod_ciudad": "SanVicenteDeTagua",
        "nom_ciudad": "San Vicente De Tagua",
        "cod_region": "06",
        "nom_region": "Libertador General Bernardo O'Higgins",
    },
    "06201": {
        "nombre":     "Pichilemu",
        "cod_ciudad": "Pichilemu",
        "nom_ciudad": "Pichilemu",
        "cod_region": "06",
        "nom_region": "Libertador General Bernardo O'Higgins",
    },
    "06202": {
        "nombre":     "La Estrella",
        "cod_ciudad": "LaEstrella",
        "nom_ciudad": "La Estrella",
        "cod_region": "06",
        "nom_region": "Libertador General Bernardo O'Higgins",
    },
    "06203": {
        "nombre":     "Litueche",
        "cod_ciudad": "Litueche",
        "nom_ciudad": "Litueche",
        "cod_region": "06",
        "nom_region": "Libertador General Bernardo O'Higgins",
    },
    "06204": {
        "nombre":     "Marchihue",
        "cod_ciudad": "Marchihue",
        "nom_ciudad": "Marchihue",
        "cod_region": "06",
        "nom_region": "Libertador General Bernardo O'Higgins",
    },
    "06205": {
        "nombre":     "Navidad",
        "cod_ciudad": "Navidad",
        "nom_ciudad": "Navidad",
        "cod_region": "06",
        "nom_region": "Libertador General Bernardo O'Higgins",
    },
    "06206": {
        "nombre":     "Paredones",
        "cod_ciudad": "Paredones",
        "nom_ciudad": "Paredones",
        "cod_region": "06",
        "nom_region": "Libertador General Bernardo O'Higgins",
    },
    "06301": {
        "nombre":     "San Fernando",
        "cod_ciudad": "SanFernando",
        "nom_ciudad": "San Fernando",
        "cod_region": "06",
        "nom_region": "Libertador General Bernardo O'Higgins",
    },
    "06302": {
        "nombre":     "Chepica",
        "cod_ciudad": "chepica",
        "nom_ciudad": "Chepica",
        "cod_region": "06",
        "nom_region": "Libertador General Bernardo O'Higgins",
    },
    "06303": {
        "nombre":     "Chimbarongo",
        "cod_ciudad": "Chimbarongo",
        "nom_ciudad": "Chimbarongo",
        "cod_region": "06",
        "nom_region": "Libertador General Bernardo O'Higgins",
    },
    "06304": {
        "nombre":     "Lolol",
        "cod_ciudad": "Lolol",
        "nom_ciudad": "Lolol",
        "cod_region": "06",
        "nom_region": "Libertador General Bernardo O'Higgins",
    },
    "06305": {
        "nombre":     "Nancagua",
        "cod_ciudad": "Nancagua",
        "nom_ciudad": "Nancagua",
        "cod_region": "06",
        "nom_region": "Libertador General Bernardo O'Higgins",
    },
    "06306": {
        "nombre":     "Palmilla",
        "cod_ciudad": "palmilla",
        "nom_ciudad": "Palmilla",
        "cod_region": "06",
        "nom_region": "Libertador General Bernardo O'Higgins",
    },
    "06307": {
        "nombre":     "Peralillo",
        "cod_ciudad": "peralillo",
        "nom_ciudad": "Peralillo",
        "cod_region": "06",
        "nom_region": "Libertador General Bernardo O'Higgins",
    },
    "06308": {
        "nombre":     "Placilla",
        "cod_ciudad": "Placilla",
        "nom_ciudad": "Placilla",
        "cod_region": "06",
        "nom_region": "Libertador General Bernardo O'Higgins",
    },
    "06309": {
        "nombre":     "Pumanque",
        "cod_ciudad": "Pumanque",
        "nom_ciudad": "Pumanque",
        "cod_region": "06",
        "nom_region": "Libertador General Bernardo O'Higgins",
    },
    "06310": {
        "nombre":     "Santa Cruz",
        "cod_ciudad": "SantaCruz",
        "nom_ciudad": "Santa Cruz",
        "cod_region": "06",
        "nom_region": "Libertador General Bernardo O'Higgins",
    },
    "07101": {
        "nombre":     "Talca",
        "cod_ciudad": "Talca",
        "nom_ciudad": "Talca",
        "cod_region": "07",
        "nom_region": "Maule",
    },
    "07102": {
        "nombre":     "Constitucion",
        "cod_ciudad": "Constitucion",
        "nom_ciudad": "Constitucion",
        "cod_region": "07",
        "nom_region": "Maule",
    },
    "07103": {
        "nombre":     "Curepto",
        "cod_ciudad": "Curepto",
        "nom_ciudad": "Curepto",
        "cod_region": "07",
        "nom_region": "Maule",
    },
    "07104": {
        "nombre":     "Empedrado",
        "cod_ciudad": "Empedrado",
        "nom_ciudad": "Empedrado",
        "cod_region": "07",
        "nom_region": "Maule",
    },
    "07105": {
        "nombre":     "Maule",
        "cod_ciudad": "Maule",
        "nom_ciudad": "Maule",
        "cod_region": "07",
        "nom_region": "Maule",
    },
    "07106": {
        "nombre":     "Pelarco",
        "cod_ciudad": "Pelarco",
        "nom_ciudad": "Pelarco",
        "cod_region": "07",
        "nom_region": "Maule",
    },
    "07107": {
        "nombre":     "Pencahue",
        "cod_ciudad": "Pencahue",
        "nom_ciudad": "Pencahue",
        "cod_region": "07",
        "nom_region": "Maule",
    },
    "07108": {
        "nombre":     "Rio Claro",
        "cod_ciudad": "RíoClaro",
        "nom_ciudad": "Río Claro",
        "cod_region": "07",
        "nom_region": "Maule",
    },
    "07109": {
        "nombre":     "San Clemente",
        "cod_ciudad": "Sanclemente",
        "nom_ciudad": "San Clemente",
        "cod_region": "07",
        "nom_region": "Maule",
    },
    "07110": {
        "nombre":     "San Rafael",
        "cod_ciudad": "SanRafael",
        "nom_ciudad": "San Rafael",
        "cod_region": "07",
        "nom_region": "Maule",
    },
    "07201": {
        "nombre":     "Cauquenes",
        "cod_ciudad": "Cauquenes",
        "nom_ciudad": "Cauquenes",
        "cod_region": "07",
        "nom_region": "Maule",
    },
    "07202": {
        "nombre":     "Chanco",
        "cod_ciudad": "Chanco",
        "nom_ciudad": "Chanco",
        "cod_region": "07",
        "nom_region": "Maule",
    },
    "07203": {
        "nombre":     "Pelluhue",
        "cod_ciudad": "Pelluhue",
        "nom_ciudad": "Pelluhue",
        "cod_region": "07",
        "nom_region": "Maule",
    },
    "07301": {
        "nombre":     "Curico",
        "cod_ciudad": "Curico",
        "nom_ciudad": "Curico",
        "cod_region": "07",
        "nom_region": "Maule",
    },
    "07302": {
        "nombre":     "Hualañe",
        "cod_ciudad": "Hualañe",
        "nom_ciudad": "Hualañe",
        "cod_region": "07",
        "nom_region": "Maule",
    },
    "07303": {
        "nombre":     "Licanten",
        "cod_ciudad": "Licantén",
        "nom_ciudad": "Licantén",
        "cod_region": "07",
        "nom_region": "Maule",
    },
    "07304": {
        "nombre":     "Molina",
        "cod_ciudad": "Molina",
        "nom_ciudad": "Molina",
        "cod_region": "07",
        "nom_region": "Maule",
    },
    "07305": {
        "nombre":     "Rauco",
        "cod_ciudad": "rauco",
        "nom_ciudad": "Rauco",
        "cod_region": "07",
        "nom_region": "Maule",
    },
    "07306": {
        "nombre":     "Romeral",
        "cod_ciudad": "Romeral",
        "nom_ciudad": "Romeral",
        "cod_region": "07",
        "nom_region": "Maule",
    },
    "07307": {
        "nombre":     "Sagrada Familia",
        "cod_ciudad": "SagradaFamilia",
        "nom_ciudad": "Sagrada Familia",
        "cod_region": "07",
        "nom_region": "Maule",
    },
    "07308": {
        "nombre":     "Teno",
        "cod_ciudad": "Teno",
        "nom_ciudad": "Teno",
        "cod_region": "07",
        "nom_region": "Maule",
    },
    "07309": {
        "nombre":     "Vichuquen",
        "cod_ciudad": "Vichuquén",
        "nom_ciudad": "Vichuquén",
        "cod_region": "07",
        "nom_region": "Maule",
    },
    "07401": {
        "nombre":     "Linares",
        "cod_ciudad": "Linares",
        "nom_ciudad": "Linares",
        "cod_region": "07",
        "nom_region": "Maule",
    },
    "07402": {
        "nombre":     "Colbun",
        "cod_ciudad": "Colbún",
        "nom_ciudad": "Colbún",
        "cod_region": "07",
        "nom_region": "Maule",
    },
    "07403": {
        "nombre":     "Longavi",
        "cod_ciudad": "Longavi",
        "nom_ciudad": "Longavi",
        "cod_region": "07",
        "nom_region": "Maule",
    },
    "07404": {
        "nombre":     "Parral",
        "cod_ciudad": "Parral",
        "nom_ciudad": "Parral",
        "cod_region": "07",
        "nom_region": "Maule",
    },
    "07405": {
        "nombre":     "Retiro",
        "cod_ciudad": "Retiro",
        "nom_ciudad": "Retiro",
        "cod_region": "07",
        "nom_region": "Maule",
    },
    "07406": {
        "nombre":     "San Javier",
        "cod_ciudad": "SanJavier",
        "nom_ciudad": "San Javier",
        "cod_region": "07",
        "nom_region": "Maule",
    },
    "07407": {
        "nombre":     "Villa Alegre",
        "cod_ciudad": "VillaAlegre",
        "nom_ciudad": "Villa Alegre",
        "cod_region": "07",
        "nom_region": "Maule",
    },
    "07408": {
        "nombre":     "Yerbas Buenas",
        "cod_ciudad": "YerbasBuenas",
        "nom_ciudad": "Yerbas Buenas",
        "cod_region": "07",
        "nom_region": "Maule",
    },
    "08101": {
        "nombre":     "Concepcion",
        "cod_ciudad": "Concepcion",
        "nom_ciudad": "Concepcion",
        "cod_region": "08",
        "nom_region": "Biobío",
    },
    "08102": {
        "nombre":     "Coronel",
        "cod_ciudad": "Coronel",
        "nom_ciudad": "Coronel",
        "cod_region": "08",
        "nom_region": "Biobío",
    },
    "08103": {
        "nombre":     "Chiguayante",
        "cod_ciudad": "Chiguayante",
        "nom_ciudad": "Chiguayante",
        "cod_region": "08",
        "nom_region": "Biobío",
    },
    "08104": {
        "nombre":     "Florida",
        "cod_ciudad": "Florida",
        "nom_ciudad": "Florida",
        "cod_region": "08",
        "nom_region": "Biobío",
    },
    "08105": {
        "nombre":     "Hualqui",
        "cod_ciudad": "Hualqui",
        "nom_ciudad": "Hualqui",
        "cod_region": "08",
        "nom_region": "Biobío",
    },
    "08106": {
        "nombre":     "Lota",
        "cod_ciudad": "Lota",
        "nom_ciudad": "Lota",
        "cod_region": "08",
        "nom_region": "Biobío",
    },
    "08107": {
        "nombre":     "Penco",
        "cod_ciudad": "Penco",
        "nom_ciudad": "Penco",
        "cod_region": "08",
        "nom_region": "Biobío",
    },
    "08108": {
        "nombre":     "San Pedro De La Paz",
        "cod_ciudad": "SanPedrodelaPaz",
        "nom_ciudad": "San Pedro de la Paz",
        "cod_region": "08",
        "nom_region": "Biobío",
    },
    "08109": {
        "nombre":     "Santa Juana",
        "cod_ciudad": "SantaJuana",
        "nom_ciudad": "Santa Juana",
        "cod_region": "08",
        "nom_region": "Biobío",
    },
    "08110": {
        "nombre":     "Talcahuano",
        "cod_ciudad": "Talcahuano",
        "nom_ciudad": "Talcahuano",
        "cod_region": "08",
        "nom_region": "Biobío",
    },
    "08111": {
        "nombre":     "Tome",
        "cod_ciudad": "Tome",
        "nom_ciudad": "Tome",
        "cod_region": "08",
        "nom_region": "Biobío",
    },
    "08201": {
        "nombre":     "Lebu",
        "cod_ciudad": "Lebu",
        "nom_ciudad": "Lebu",
        "cod_region": "08",
        "nom_region": "Biobío",
    },
    "08202": {
        "nombre":     "Arauco",
        "cod_ciudad": "Arauco",
        "nom_ciudad": "Arauco",
        "cod_region": "08",
        "nom_region": "Biobío",
    },
    "08203": {
        "nombre":     "Cañete",
        "cod_ciudad": "Cañete",
        "nom_ciudad": "Cañete",
        "cod_region": "08",
        "nom_region": "Biobío",
    },
    "08204": {
        "nombre":     "Contulmo",
        "cod_ciudad": "Contulmo",
        "nom_ciudad": "Contulmo",
        "cod_region": "08",
        "nom_region": "Biobío",
    },
    "08205": {
        "nombre":     "Curanilahue",
        "cod_ciudad": "Curanilahue",
        "nom_ciudad": "Curanilahue",
        "cod_region": "08",
        "nom_region": "Biobío",
    },
    "08206": {
        "nombre":     "Los Alamos",
        "cod_ciudad": "LosAlamos",
        "nom_ciudad": "Los Alamos",
        "cod_region": "08",
        "nom_region": "Biobío",
    },
    "08207": {
        "nombre":     "Tirua",
        "cod_ciudad": "Tirua",
        "nom_ciudad": "Tirua",
        "cod_region": "08",
        "nom_region": "Biobío",
    },
    "08112": {
        "nombre":     "Hualpen",
        "cod_ciudad": "Hualpen",
        "nom_ciudad": "Hualpen",
        "cod_region": "08",
        "nom_region": "Biobío",
    },
    "08301": {
        "nombre":     "Los Angeles",
        "cod_ciudad": "LosAngeles",
        "nom_ciudad": "Los Angeles",
        "cod_region": "08",
        "nom_region": "Biobío",
    },
    "08302": {
        "nombre":     "Antuco",
        "cod_ciudad": "Antuco",
        "nom_ciudad": "Antuco",
        "cod_region": "08",
        "nom_region": "Biobío",
    },
    "08303": {
        "nombre":     "Cabrero",
        "cod_ciudad": "Cabrero",
        "nom_ciudad": "Cabrero",
        "cod_region": "08",
        "nom_region": "Biobío",
    },
    "08304": {
        "nombre":     "Laja",
        "cod_ciudad": "Laja",
        "nom_ciudad": "Laja",
        "cod_region": "08",
        "nom_region": "Biobío",
    },
    "08305": {
        "nombre":     "Mulchen",
        "cod_ciudad": "Mulchen",
        "nom_ciudad": "Mulchen",
        "cod_region": "08",
        "nom_region": "Biobío",
    },
    "08306": {
        "nombre":     "Nacimiento",
        "cod_ciudad": "Nacimiento",
        "nom_ciudad": "Nacimiento",
        "cod_region": "08",
        "nom_region": "Biobío",
    },
    "08307": {
        "nombre":     "Negrete",
        "cod_ciudad": "Negrete",
        "nom_ciudad": "Negrete",
        "cod_region": "08",
        "nom_region": "Biobío",
    },
    "08308": {
        "nombre":     "Quilaco",
        "cod_ciudad": "Quilaco",
        "nom_ciudad": "Quilaco",
        "cod_region": "08",
        "nom_region": "Biobío",
    },
    "08309": {
        "nombre":     "Quilleco",
        "cod_ciudad": "Quilleco",
        "nom_ciudad": "Quilleco",
        "cod_region": "08",
        "nom_region": "Biobío",
    },
    "08310": {
        "nombre":     "San Rosendo",
        "cod_ciudad": "SanRosendo",
        "nom_ciudad": "San Rosendo",
        "cod_region": "08",
        "nom_region": "Biobío",
    },
    "08311": {
        "nombre":     "Santa Barbara",
        "cod_ciudad": "SantaBarbara",
        "nom_ciudad": "Santa Barbara",
        "cod_region": "08",
        "nom_region": "Biobío",
    },
    "08312": {
        "nombre":     "Tucapel",
        "cod_ciudad": "tucapel",
        "nom_ciudad": "Tucapel",
        "cod_region": "08",
        "nom_region": "Biobío",
    },
    "08313": {
        "nombre":     "Yumbel",
        "cod_ciudad": "Yumbel",
        "nom_ciudad": "Yumbel",
        "cod_region": "08",
        "nom_region": "Biobío",
    },
    "08314": {
        "nombre":     "Alto Biobio",
        "cod_ciudad": "AltoBiobío",
        "nom_ciudad": "Alto Biobío",
        "cod_region": "08",
        "nom_region": "Biobío",
    },
    "16101": {
        "nombre":     "Chillan",
        "cod_ciudad": "Chillan",
        "nom_ciudad": "Chillán",
        "cod_region": "16",
        "nom_region": "Ñuble",
    },
    "16102": {
        "nombre":     "Bulnes",
        "cod_ciudad": "Bulnes",
        "nom_ciudad": "Bulnes",
        "cod_region": "16",
        "nom_region": "Ñuble",
    },
    "16202": {
        "nombre":     "Cobquecura",
        "cod_ciudad": "Cobquecura",
        "nom_ciudad": "Cobquecura",
        "cod_region": "16",
        "nom_region": "Ñuble",
    },
    "16203": {
        "nombre":     "Coelemu",
        "cod_ciudad": "Coelemu",
        "nom_ciudad": "Coelemu",
        "cod_region": "16",
        "nom_region": "Ñuble",
    },
    "16302": {
        "nombre":     "Coihueco",
        "cod_ciudad": "Coihueco",
        "nom_ciudad": "Coihueco",
        "cod_region": "16",
        "nom_region": "Ñuble",
    },
    "16103": {
        "nombre":     "Chillan Viejo",
        "cod_ciudad": "ChillánViejo",
        "nom_ciudad": "Chillán Viejo",
        "cod_region": "16",
        "nom_region": "Ñuble",
    },
    "16104": {
        "nombre":     "El Carmen",
        "cod_ciudad": "ElCarmen",
        "nom_ciudad": "El Carmen",
        "cod_region": "16",
        "nom_region": "Ñuble",
    },
    "16204": {
        "nombre":     "Ninhue",
        "cod_ciudad": "Ninhue",
        "nom_ciudad": "Ninhue",
        "cod_region": "16",
        "nom_region": "Ñuble",
    },
    "16303": {
        "nombre":     "Ñiquen",
        "cod_ciudad": "Ñiquén",
        "nom_ciudad": "Ñiquén",
        "cod_region": "16",
        "nom_region": "Ñuble",
    },
    "16105": {
        "nombre":     "Pemuco",
        "cod_ciudad": "Pemuco",
        "nom_ciudad": "Pemuco",
        "cod_region": "16",
        "nom_region": "Ñuble",
    },
    "16106": {
        "nombre":     "Pinto",
        "cod_ciudad": "Pinto",
        "nom_ciudad": "Pinto",
        "cod_region": "16",
        "nom_region": "Ñuble",
    },
    "16205": {
        "nombre":     "Portezuelo",
        "cod_ciudad": "Portezuelo",
        "nom_ciudad": "Portezuelo",
        "cod_region": "16",
        "nom_region": "Ñuble",
    },
    "16107": {
        "nombre":     "Quillon",
        "cod_ciudad": "Quillon",
        "nom_ciudad": "Quillon",
        "cod_region": "16",
        "nom_region": "Ñuble",
    },
    "16201": {
        "nombre":     "Quirihue",
        "cod_ciudad": "Quirihue",
        "nom_ciudad": "Quirihue",
        "cod_region": "16",
        "nom_region": "Ñuble",
    },
    "16206": {
        "nombre":     "Ranquil",
        "cod_ciudad": "Ránquil",
        "nom_ciudad": "Ránquil",
        "cod_region": "16",
        "nom_region": "Ñuble",
    },
    "16301": {
        "nombre":     "San Carlos",
        "cod_ciudad": "SanCarlosnuble",
        "nom_ciudad": "San Carlos Ñuble",
        "cod_region": "16",
        "nom_region": "Ñuble",
    },
    "16304": {
        "nombre":     "San Fabian",
        "cod_ciudad": "SanFabián",
        "nom_ciudad": "San Fabián",
        "cod_region": "16",
        "nom_region": "Ñuble",
    },
    "16108": {
        "nombre":     "San Ignacio",
        "cod_ciudad": "SanIgnacio",
        "nom_ciudad": "San Ignacio",
        "cod_region": "16",
        "nom_region": "Ñuble",
    },
    "16305": {
        "nombre":     "San Nicolas",
        "cod_ciudad": "SanNicolás",
        "nom_ciudad": "San Nicolás",
        "cod_region": "16",
        "nom_region": "Ñuble",
    },
    "16207": {
        "nombre":     "Treguaco",
        "cod_ciudad": "Treguaco",
        "nom_ciudad": "Treguaco",
        "cod_region": "16",
        "nom_region": "Ñuble",
    },
    "16109": {
        "nombre":     "Yungay",
        "cod_ciudad": "Yungay",
        "nom_ciudad": "Yungay",
        "cod_region": "16",
        "nom_region": "Ñuble",
    },
    "09101": {
        "nombre":     "Temuco",
        "cod_ciudad": "Temuco",
        "nom_ciudad": "Temuco",
        "cod_region": "09",
        "nom_region": "La Araucanía",
    },
    "09102": {
        "nombre":     "Carahue",
        "cod_ciudad": "Carahue",
        "nom_ciudad": "Carahue",
        "cod_region": "09",
        "nom_region": "La Araucanía",
    },
    "09103": {
        "nombre":     "Cunco",
        "cod_ciudad": "Cunco",
        "nom_ciudad": "Cunco",
        "cod_region": "09",
        "nom_region": "La Araucanía",
    },
    "09104": {
        "nombre":     "Curarrehue",
        "cod_ciudad": "Curarrehue",
        "nom_ciudad": "Curarrehue",
        "cod_region": "09",
        "nom_region": "La Araucanía",
    },
    "09105": {
        "nombre":     "Freire",
        "cod_ciudad": "Freire",
        "nom_ciudad": "Freire",
        "cod_region": "09",
        "nom_region": "La Araucanía",
    },
    "09106": {
        "nombre":     "Galvarino",
        "cod_ciudad": "Galvarino",
        "nom_ciudad": "Galvarino",
        "cod_region": "09",
        "nom_region": "La Araucanía",
    },
    "09107": {
        "nombre":     "Gorbea",
        "cod_ciudad": "Gorbea",
        "nom_ciudad": "Gorbea",
        "cod_region": "09",
        "nom_region": "La Araucanía",
    },
    "09108": {
        "nombre":     "Lautaro",
        "cod_ciudad": "Lautaro",
        "nom_ciudad": "Lautaro",
        "cod_region": "09",
        "nom_region": "La Araucanía",
    },
    "09109": {
        "nombre":     "Loncoche",
        "cod_ciudad": "Loncoche",
        "nom_ciudad": "Loncoche",
        "cod_region": "09",
        "nom_region": "La Araucanía",
    },
    "09110": {
        "nombre":     "Melipeuco",
        "cod_ciudad": "Melipeuco",
        "nom_ciudad": "Melipeuco",
        "cod_region": "09",
        "nom_region": "La Araucanía",
    },
    "09111": {
        "nombre":     "Nueva Imperial",
        "cod_ciudad": "NuevaImperial",
        "nom_ciudad": "Nueva Imperial",
        "cod_region": "09",
        "nom_region": "La Araucanía",
    },
    "09112": {
        "nombre":     "Padre Las Casas",
        "cod_ciudad": "PadreLasCasas",
        "nom_ciudad": "Padre Las Casas",
        "cod_region": "09",
        "nom_region": "La Araucanía",
    },
    "09113": {
        "nombre":     "Perquenco",
        "cod_ciudad": "Perquenco",
        "nom_ciudad": "Perquenco",
        "cod_region": "09",
        "nom_region": "La Araucanía",
    },
    "09114": {
        "nombre":     "Pitrufquen",
        "cod_ciudad": "pitrufquen",
        "nom_ciudad": "Pitrufquen",
        "cod_region": "09",
        "nom_region": "La Araucanía",
    },
    "09115": {
        "nombre":     "Pucon",
        "cod_ciudad": "Pucon",
        "nom_ciudad": "Pucon",
        "cod_region": "09",
        "nom_region": "La Araucanía",
    },
    "09116": {
        "nombre":     "Saavedra",
        "cod_ciudad": "Saavedra",
        "nom_ciudad": "Saavedra",
        "cod_region": "09",
        "nom_region": "La Araucanía",
    },
    "09117": {
        "nombre":     "Teodoro Schmidt",
        "cod_ciudad": "TeodoroSchmidt",
        "nom_ciudad": "Teodoro Schmidt",
        "cod_region": "09",
        "nom_region": "La Araucanía",
    },
    "09118": {
        "nombre":     "Tolten",
        "cod_ciudad": "Toltén",
        "nom_ciudad": "Toltén",
        "cod_region": "09",
        "nom_region": "La Araucanía",
    },
    "09119": {
        "nombre":     "Vilcun",
        "cod_ciudad": "Vilcún",
        "nom_ciudad": "Vilcún",
        "cod_region": "09",
        "nom_region": "La Araucanía",
    },
    "09120": {
        "nombre":     "Villarrica",
        "cod_ciudad": "Villarrica",
        "nom_ciudad": "Villarrica",
        "cod_region": "09",
        "nom_region": "La Araucanía",
    },
    "09121": {
        "nombre":     "Cholchol",
        "cod_ciudad": "Cholchol",
        "nom_ciudad": "Cholchol",
        "cod_region": "09",
        "nom_region": "La Araucanía",
    },
    "09201": {
        "nombre":     "Angol",
        "cod_ciudad": "Angol",
        "nom_ciudad": "Angol",
        "cod_region": "09",
        "nom_region": "La Araucanía",
    },
    "09202": {
        "nombre":     "Collipulli",
        "cod_ciudad": "Collipulli",
        "nom_ciudad": "Collipulli",
        "cod_region": "09",
        "nom_region": "La Araucanía",
    },
    "09203": {
        "nombre":     "Curacautin",
        "cod_ciudad": "Curacautin",
        "nom_ciudad": "Curacautin",
        "cod_region": "09",
        "nom_region": "La Araucanía",
    },
    "09204": {
        "nombre":     "Ercilla",
        "cod_ciudad": "Ercilla",
        "nom_ciudad": "Ercilla",
        "cod_region": "09",
        "nom_region": "La Araucanía",
    },
    "09205": {
        "nombre":     "Lonquimay",
        "cod_ciudad": "Lonquimay",
        "nom_ciudad": "Lonquimay",
        "cod_region": "09",
        "nom_region": "La Araucanía",
    },
    "09206": {
        "nombre":     "Los Sauces",
        "cod_ciudad": "LosSauces",
        "nom_ciudad": "Los Sauces",
        "cod_region": "09",
        "nom_region": "La Araucanía",
    },
    "09207": {
        "nombre":     "Lumaco",
        "cod_ciudad": "Lumaco",
        "nom_ciudad": "Lumaco",
        "cod_region": "09",
        "nom_region": "La Araucanía",
    },
    "09208": {
        "nombre":     "Puren",
        "cod_ciudad": "Puren",
        "nom_ciudad": "Puren",
        "cod_region": "09",
        "nom_region": "La Araucanía",
    },
    "09209": {
        "nombre":     "Renaico",
        "cod_ciudad": "Renaico",
        "nom_ciudad": "Renaico",
        "cod_region": "09",
        "nom_region": "La Araucanía",
    },
    "09210": {
        "nombre":     "Traiguen",
        "cod_ciudad": "Traiguen",
        "nom_ciudad": "Traiguen",
        "cod_region": "09",
        "nom_region": "La Araucanía",
    },
    "09211": {
        "nombre":     "Victoria",
        "cod_ciudad": "Victoria",
        "nom_ciudad": "Victoria",
        "cod_region": "09",
        "nom_region": "La Araucanía",
    },
    "10101": {
        "nombre":     "Puerto Montt",
        "cod_ciudad": "PuertoMontt",
        "nom_ciudad": "Puerto Montt",
        "cod_region": "10",
        "nom_region": "Los Lagos",
    },
    "10102": {
        "nombre":     "Calbuco",
        "cod_ciudad": "Calbuco",
        "nom_ciudad": "Calbuco",
        "cod_region": "10",
        "nom_region": "Los Lagos",
    },
    "10103": {
        "nombre":     "Cochamo",
        "cod_ciudad": "Cochamó",
        "nom_ciudad": "Cochamó",
        "cod_region": "10",
        "nom_region": "Los Lagos",
    },
    "10104": {
        "nombre":     "Fresia",
        "cod_ciudad": "Fresia",
        "nom_ciudad": "Fresia",
        "cod_region": "10",
        "nom_region": "Los Lagos",
    },
    "10105": {
        "nombre":     "Frutillar",
        "cod_ciudad": "frutillar",
        "nom_ciudad": "Frutillar",
        "cod_region": "10",
        "nom_region": "Los Lagos",
    },
    "10106": {
        "nombre":     "Los Muermos",
        "cod_ciudad": "LosMuermos",
        "nom_ciudad": "Los Muermos",
        "cod_region": "10",
        "nom_region": "Los Lagos",
    },
    "10107": {
        "nombre":     "Llanquihue",
        "cod_ciudad": "llanquihue",
        "nom_ciudad": "LLanquihue",
        "cod_region": "10",
        "nom_region": "Los Lagos",
    },
    "10108": {
        "nombre":     "Maullin",
        "cod_ciudad": "Maullin",
        "nom_ciudad": "Maullin",
        "cod_region": "10",
        "nom_region": "Los Lagos",
    },
    "10109": {
        "nombre":     "Puerto Varas",
        "cod_ciudad": "PuertoVaras",
        "nom_ciudad": "Puerto Varas",
        "cod_region": "10",
        "nom_region": "Los Lagos",
    },
    "10201": {
        "nombre":     "Castro",
        "cod_ciudad": "Castro",
        "nom_ciudad": "Castro",
        "cod_region": "10",
        "nom_region": "Los Lagos",
    },
    "10202": {
        "nombre":     "Ancud",
        "cod_ciudad": "Ancud",
        "nom_ciudad": "Ancud",
        "cod_region": "10",
        "nom_region": "Los Lagos",
    },
    "10203": {
        "nombre":     "Chonchi",
        "cod_ciudad": "Chonchi",
        "nom_ciudad": "Chonchi",
        "cod_region": "10",
        "nom_region": "Los Lagos",
    },
    "10204": {
        "nombre":     "Curaco De Velez",
        "cod_ciudad": "CuracodeVélez",
        "nom_ciudad": "Curaco de Vélez",
        "cod_region": "10",
        "nom_region": "Los Lagos",
    },
    "10205": {
        "nombre":     "Dalcahue",
        "cod_ciudad": "Dalcahue",
        "nom_ciudad": "Dalcahue",
        "cod_region": "10",
        "nom_region": "Los Lagos",
    },
    "10206": {
        "nombre":     "Puqueldon",
        "cod_ciudad": "Puqueldón",
        "nom_ciudad": "Puqueldón",
        "cod_region": "10",
        "nom_region": "Los Lagos",
    },
    "10207": {
        "nombre":     "Queilen",
        "cod_ciudad": "Queilén",
        "nom_ciudad": "Queilén",
        "cod_region": "10",
        "nom_region": "Los Lagos",
    },
    "10208": {
        "nombre":     "Quellon",
        "cod_ciudad": "Quellon",
        "nom_ciudad": "Quellon",
        "cod_region": "10",
        "nom_region": "Los Lagos",
    },
    "10209": {
        "nombre":     "Quemchi",
        "cod_ciudad": "Quemchi",
        "nom_ciudad": "Quemchi",
        "cod_region": "10",
        "nom_region": "Los Lagos",
    },
    "10210": {
        "nombre":     "Quinchao",
        "cod_ciudad": "quinchao",
        "nom_ciudad": "Quinchao",
        "cod_region": "10",
        "nom_region": "Los Lagos",
    },
    "10301": {
        "nombre":     "Osorno",
        "cod_ciudad": "Osorno",
        "nom_ciudad": "Osorno",
        "cod_region": "10",
        "nom_region": "Los Lagos",
    },
    "10302": {
        "nombre":     "Puerto Octay",
        "cod_ciudad": "PuertoOctay",
        "nom_ciudad": "Puerto Octay",
        "cod_region": "10",
        "nom_region": "Los Lagos",
    },
    "10303": {
        "nombre":     "Purranque",
        "cod_ciudad": "Purranque",
        "nom_ciudad": "Purranque",
        "cod_region": "10",
        "nom_region": "Los Lagos",
    },
    "10304": {
        "nombre":     "Puyehue",
        "cod_ciudad": "Puyehue",
        "nom_ciudad": "Puyehue",
        "cod_region": "10",
        "nom_region": "Los Lagos",
    },
    "10305": {
        "nombre":     "Rio Negro",
        "cod_ciudad": "RioNegro",
        "nom_ciudad": "Río Negro",
        "cod_region": "10",
        "nom_region": "Los Lagos",
    },
    "10306": {
        "nombre":     "San Juan De La Costa",
        "cod_ciudad": "SanJuandelaCosta",
        "nom_ciudad": "San Juan de la Costa",
        "cod_region": "10",
        "nom_region": "Los Lagos",
    },
    "10307": {
        "nombre":     "San Pablo",
        "cod_ciudad": "SanPablo",
        "nom_ciudad": "San Pablo",
        "cod_region": "10",
        "nom_region": "Los Lagos",
    },
    "10401": {
        "nombre":     "Chaiten",
        "cod_ciudad": "Chaiten",
        "nom_ciudad": "Chaiten",
        "cod_region": "10",
        "nom_region": "Los Lagos",
    },
    "10402": {
        "nombre":     "Futaleufu",
        "cod_ciudad": "Futaleufú",
        "nom_ciudad": "Futaleufú",
        "cod_region": "10",
        "nom_region": "Los Lagos",
    },
    "10403": {
        "nombre":     "Hualaihue",
        "cod_ciudad": "Hualaihué",
        "nom_ciudad": "Hualaihué",
        "cod_region": "10",
        "nom_region": "Los Lagos",
    },
    "10404": {
        "nombre":     "Palena",
        "cod_ciudad": "Palena",
        "nom_ciudad": "Palena",
        "cod_region": "10",
        "nom_region": "Los Lagos",
    },
    "14101": {
        "nombre":     "Valdivia",
        "cod_ciudad": "Valdivia",
        "nom_ciudad": "Valdivia",
        "cod_region": "14",
        "nom_region": "Los Ríos",
    },
    "14102": {
        "nombre":     "Corral",
        "cod_ciudad": "Corral",
        "nom_ciudad": "Corral",
        "cod_region": "14",
        "nom_region": "Los Ríos",
    },
    "14202": {
        "nombre":     "Futrono",
        "cod_ciudad": "Futrono",
        "nom_ciudad": "Futrono",
        "cod_region": "14",
        "nom_region": "Los Ríos",
    },
    "14201": {
        "nombre":     "La Union",
        "cod_ciudad": "LaUnion",
        "nom_ciudad": "La Union",
        "cod_region": "14",
        "nom_region": "Los Ríos",
    },
    "14203": {
        "nombre":     "Lago Ranco",
        "cod_ciudad": "lagoranco",
        "nom_ciudad": "Lago Ranco",
        "cod_region": "14",
        "nom_region": "Los Ríos",
    },
    "14103": {
        "nombre":     "Lanco",
        "cod_ciudad": "Lanco",
        "nom_ciudad": "Lanco",
        "cod_region": "14",
        "nom_region": "Los Ríos",
    },
    "14104": {
        "nombre":     "Los Lagos",
        "cod_ciudad": "LosLagos",
        "nom_ciudad": "Los Lagos",
        "cod_region": "14",
        "nom_region": "Los Ríos",
    },
    "14105": {
        "nombre":     "Mafil",
        "cod_ciudad": "Mafil",
        "nom_ciudad": "Mafil",
        "cod_region": "14",
        "nom_region": "Los Ríos",
    },
    "14106": {
        "nombre":     "Mariquina",
        "cod_ciudad": "SanJoseDelaMariquina",
        "nom_ciudad": "San Jose De La Mariquina",
        "cod_region": "14",
        "nom_region": "Los Ríos",
    },
    "14107": {
        "nombre":     "Paillaco",
        "cod_ciudad": "paillaco",
        "nom_ciudad": "Paillaco",
        "cod_region": "14",
        "nom_region": "Los Ríos",
    },
    "14108": {
        "nombre":     "Panguipulli",
        "cod_ciudad": "Panguipulli",
        "nom_ciudad": "Panguipulli",
        "cod_region": "14",
        "nom_region": "Los Ríos",
    },
    "14204": {
        "nombre":     "Rio Bueno",
        "cod_ciudad": "RioBueno",
        "nom_ciudad": "Río Bueno",
        "cod_region": "14",
        "nom_region": "Los Ríos",
    },
    "11101": {
        "nombre":     "Coyhaique",
        "cod_ciudad": "Coyhaique",
        "nom_ciudad": "Coyhaique",
        "cod_region": "11",
        "nom_region": "Aysén del General Carlos Ibáñez del Campo",
    },
    "11102": {
        "nombre":     "Lago Verde",
        "cod_ciudad": "LagoVerde",
        "nom_ciudad": "Lago Verde",
        "cod_region": "11",
        "nom_region": "Aysén del General Carlos Ibáñez del Campo",
    },
    "11201": {
        "nombre":     "Aysen",
        "cod_ciudad": "PuertoAysen",
        "nom_ciudad": "Aysén",
        "cod_region": "11",
        "nom_region": "Aysén del General Carlos Ibáñez del Campo",
    },
    "11202": {
        "nombre":     "Cisnes",
        "cod_ciudad": "Cisnes",
        "nom_ciudad": "Cisnes",
        "cod_region": "11",
        "nom_region": "Aysén del General Carlos Ibáñez del Campo",
    },
    "11203": {
        "nombre":     "Guaitecas",
        "cod_ciudad": "Guaitecas",
        "nom_ciudad": "Guaitecas",
        "cod_region": "11",
        "nom_region": "Aysén del General Carlos Ibáñez del Campo",
    },
    "11301": {
        "nombre":     "Cochrane",
        "cod_ciudad": "Cochrane",
        "nom_ciudad": "Cochrane",
        "cod_region": "11",
        "nom_region": "Aysén del General Carlos Ibáñez del Campo",
    },
    "11302": {
        "nombre":     "O'Higgins",
        "cod_ciudad": "O'Higgins",
        "nom_ciudad": "O'Higgins",
        "cod_region": "11",
        "nom_region": "Aysén del General Carlos Ibáñez del Campo",
    },
    "11303": {
        "nombre":     "Tortel",
        "cod_ciudad": "Tortel",
        "nom_ciudad": "Tortel",
        "cod_region": "11",
        "nom_region": "Aysén del General Carlos Ibáñez del Campo",
    },
    "11401": {
        "nombre":     "Chile Chico",
        "cod_ciudad": "ChileChico",
        "nom_ciudad": "Chile Chico",
        "cod_region": "11",
        "nom_region": "Aysén del General Carlos Ibáñez del Campo",
    },
    "11402": {
        "nombre":     "Rio Ibañez",
        "cod_ciudad": "RioIbañez",
        "nom_ciudad": "Río Ibañez",
        "cod_region": "11",
        "nom_region": "Aysén del General Carlos Ibáñez del Campo",
    },
    "12101": {
        "nombre":     "Punta Arenas",
        "cod_ciudad": "PuntaArenas",
        "nom_ciudad": "Punta Arenas",
        "cod_region": "12",
        "nom_region": "Magallanes y de la Antártica Chilena",
    },
    "12102": {
        "nombre":     "Laguna Blanca",
        "cod_ciudad": "LagunaBlanca",
        "nom_ciudad": "Laguna Blanca",
        "cod_region": "12",
        "nom_region": "Magallanes y de la Antártica Chilena",
    },
    "12103": {
        "nombre":     "Rio Verde",
        "cod_ciudad": "RioVerde",
        "nom_ciudad": "Río Verde",
        "cod_region": "12",
        "nom_region": "Magallanes y de la Antártica Chilena",
    },
    "12104": {
        "nombre":     "San Gregorio",
        "cod_ciudad": "SanGregorio",
        "nom_ciudad": "San Gregorio",
        "cod_region": "12",
        "nom_region": "Magallanes y de la Antártica Chilena",
    },
    "12201": {
        "nombre":     "Cabo De Hornos",
        "cod_ciudad": "CabodeHornos(Ex-Navarino)",
        "nom_ciudad": "Cabo de Hornos",
        "cod_region": "12",
        "nom_region": "Magallanes y de la Antártica Chilena",
    },
    "12202": {
        "nombre":     "Antartica",
        "cod_ciudad": "Antártica",
        "nom_ciudad": "Antártica",
        "cod_region": "12",
        "nom_region": "Magallanes y de la Antártica Chilena",
    },
    "12301": {
        "nombre":     "Porvenir",
        "cod_ciudad": "Porvenir",
        "nom_ciudad": "Porvenir",
        "cod_region": "12",
        "nom_region": "Magallanes y de la Antártica Chilena",
    },
    "12302": {
        "nombre":     "Primavera",
        "cod_ciudad": "Primavera",
        "nom_ciudad": "Primavera",
        "cod_region": "12",
        "nom_region": "Magallanes y de la Antártica Chilena",
    },
    "12303": {
        "nombre":     "Timaukel",
        "cod_ciudad": "Timaukel",
        "nom_ciudad": "Timaukel",
        "cod_region": "12",
        "nom_region": "Magallanes y de la Antártica Chilena",
    },
    "12401": {
        "nombre":     "Natales",
        "cod_ciudad": "PuertoNatales",
        "nom_ciudad": "Puerto Natales",
        "cod_region": "12",
        "nom_region": "Magallanes y de la Antártica Chilena",
    },
    "12402": {
        "nombre":     "Torres Del Paine",
        "cod_ciudad": "TorresdelPaine",
        "nom_ciudad": "Torres del Paine",
        "cod_region": "12",
        "nom_region": "Magallanes y de la Antártica Chilena",
    },
    "13101": {
        "nombre":     "Santiago",
        "cod_ciudad": "Santiago",
        "nom_ciudad": "Santiago",
        "cod_region": "13",
        "nom_region": "Metropolitana de Santiago",
    },
    "13102": {
        "nombre":     "Cerrillos",
        "cod_ciudad": "Cerrillos",
        "nom_ciudad": "Cerrillos",
        "cod_region": "13",
        "nom_region": "Metropolitana de Santiago",
    },
    "13103": {
        "nombre":     "Cerro Navia",
        "cod_ciudad": "CerroNavia",
        "nom_ciudad": "Cerro Navia",
        "cod_region": "13",
        "nom_region": "Metropolitana de Santiago",
    },
    "13104": {
        "nombre":     "Conchali",
        "cod_ciudad": "Conchali",
        "nom_ciudad": "Conchali",
        "cod_region": "13",
        "nom_region": "Metropolitana de Santiago",
    },
    "13105": {
        "nombre":     "El Bosque",
        "cod_ciudad": "ElBosque",
        "nom_ciudad": "El Bosque",
        "cod_region": "13",
        "nom_region": "Metropolitana de Santiago",
    },
    "13106": {
        "nombre":     "Estacion Central",
        "cod_ciudad": "EstacionCentral",
        "nom_ciudad": "Estacion Central",
        "cod_region": "13",
        "nom_region": "Metropolitana de Santiago",
    },
    "13107": {
        "nombre":     "Huechuraba",
        "cod_ciudad": "Huechuraba",
        "nom_ciudad": "Huechuraba",
        "cod_region": "13",
        "nom_region": "Metropolitana de Santiago",
    },
    "13108": {
        "nombre":     "Independencia",
        "cod_ciudad": "Independencia",
        "nom_ciudad": "Independencia",
        "cod_region": "13",
        "nom_region": "Metropolitana de Santiago",
    },
    "13109": {
        "nombre":     "La Cisterna",
        "cod_ciudad": "LaCisterna",
        "nom_ciudad": "La Cisterna",
        "cod_region": "13",
        "nom_region": "Metropolitana de Santiago",
    },
    "13110": {
        "nombre":     "La Florida",
        "cod_ciudad": "LaFlorida",
        "nom_ciudad": "La Florida",
        "cod_region": "13",
        "nom_region": "Metropolitana de Santiago",
    },
    "13111": {
        "nombre":     "La Granja",
        "cod_ciudad": "LaGranja",
        "nom_ciudad": "La Granja",
        "cod_region": "13",
        "nom_region": "Metropolitana de Santiago",
    },
    "13112": {
        "nombre":     "La Pintana",
        "cod_ciudad": "LaPintana",
        "nom_ciudad": "La Pintana",
        "cod_region": "13",
        "nom_region": "Metropolitana de Santiago",
    },
    "13113": {
        "nombre":     "La Reina",
        "cod_ciudad": "LaReina",
        "nom_ciudad": "La Reina",
        "cod_region": "13",
        "nom_region": "Metropolitana de Santiago",
    },
    "13114": {
        "nombre":     "Las Condes",
        "cod_ciudad": "LasCondes",
        "nom_ciudad": "Las Condes",
        "cod_region": "13",
        "nom_region": "Metropolitana de Santiago",
    },
    "13115": {
        "nombre":     "Lo Barnechea",
        "cod_ciudad": "LoBarnechea",
        "nom_ciudad": "Lo Barnechea",
        "cod_region": "13",
        "nom_region": "Metropolitana de Santiago",
    },
    "13116": {
        "nombre":     "Lo Espejo",
        "cod_ciudad": "LoEspejo",
        "nom_ciudad": "Lo Espejo",
        "cod_region": "13",
        "nom_region": "Metropolitana de Santiago",
    },
    "13117": {
        "nombre":     "Lo Prado",
        "cod_ciudad": "LoPrado",
        "nom_ciudad": "Lo Prado",
        "cod_region": "13",
        "nom_region": "Metropolitana de Santiago",
    },
    "13118": {
        "nombre":     "Macul",
        "cod_ciudad": "Macul",
        "nom_ciudad": "Macul",
        "cod_region": "13",
        "nom_region": "Metropolitana de Santiago",
    },
    "13119": {
        "nombre":     "Maipu",
        "cod_ciudad": "Maipu",
        "nom_ciudad": "Maipu",
        "cod_region": "13",
        "nom_region": "Metropolitana de Santiago",
    },
    "13120": {
        "nombre":     "Ñuñoa",
        "cod_ciudad": "Ñuñoa",
        "nom_ciudad": "Ñuñoa",
        "cod_region": "13",
        "nom_region": "Metropolitana de Santiago",
    },
    "13121": {
        "nombre":     "Pedro Aguirre Cerda",
        "cod_ciudad": "PedroAguirreCerda",
        "nom_ciudad": "Pedro Aguirre Cerda",
        "cod_region": "13",
        "nom_region": "Metropolitana de Santiago",
    },
    "13122": {
        "nombre":     "Peñalolen",
        "cod_ciudad": "Peñalolen",
        "nom_ciudad": "Peñalolen",
        "cod_region": "13",
        "nom_region": "Metropolitana de Santiago",
    },
    "13123": {
        "nombre":     "Providencia",
        "cod_ciudad": "Providencia",
        "nom_ciudad": "Providencia",
        "cod_region": "13",
        "nom_region": "Metropolitana de Santiago",
    },
    "13124": {
        "nombre":     "Pudahuel",
        "cod_ciudad": "Pudahuel",
        "nom_ciudad": "Pudahuel",
        "cod_region": "13",
        "nom_region": "Metropolitana de Santiago",
    },
    "13125": {
        "nombre":     "Quilicura",
        "cod_ciudad": "Quilicura",
        "nom_ciudad": "Quilicura",
        "cod_region": "13",
        "nom_region": "Metropolitana de Santiago",
    },
    "13126": {
        "nombre":     "Quinta Normal",
        "cod_ciudad": "QuintaNormal",
        "nom_ciudad": "Quinta Normal",
        "cod_region": "13",
        "nom_region": "Metropolitana de Santiago",
    },
    "13127": {
        "nombre":     "Recoleta",
        "cod_ciudad": "Recoleta",
        "nom_ciudad": "Recoleta",
        "cod_region": "13",
        "nom_region": "Metropolitana de Santiago",
    },
    "13128": {
        "nombre":     "Renca",
        "cod_ciudad": "Renca",
        "nom_ciudad": "Renca",
        "cod_region": "13",
        "nom_region": "Metropolitana de Santiago",
    },
    "13129": {
        "nombre":     "San Joaquin",
        "cod_ciudad": "SanJoaquin",
        "nom_ciudad": "San Joaquin",
        "cod_region": "13",
        "nom_region": "Metropolitana de Santiago",
    },
    "13130": {
        "nombre":     "San Miguel",
        "cod_ciudad": "SanMiguel",
        "nom_ciudad": "San Miguel",
        "cod_region": "13",
        "nom_region": "Metropolitana de Santiago",
    },
    "13131": {
        "nombre":     "San Ramon",
        "cod_ciudad": "SanRamon",
        "nom_ciudad": "San Ramon",
        "cod_region": "13",
        "nom_region": "Metropolitana de Santiago",
    },
    "13132": {
        "nombre":     "Vitacura",
        "cod_ciudad": "Vitacura",
        "nom_ciudad": "Vitacura",
        "cod_region": "13",
        "nom_region": "Metropolitana de Santiago",
    },
    "13201": {
        "nombre":     "Puente Alto",
        "cod_ciudad": "PuenteAlto",
        "nom_ciudad": "Puente Alto",
        "cod_region": "13",
        "nom_region": "Metropolitana de Santiago",
    },
    "13202": {
        "nombre":     "Pirque",
        "cod_ciudad": "Pirque",
        "nom_ciudad": "Pirque",
        "cod_region": "13",
        "nom_region": "Metropolitana de Santiago",
    },
    "13203": {
        "nombre":     "San Jose De Maipo",
        "cod_ciudad": "SanJoseDeMaipo",
        "nom_ciudad": "San Jose De Maipo",
        "cod_region": "13",
        "nom_region": "Metropolitana de Santiago",
    },
    "13301": {
        "nombre":     "Colina",
        "cod_ciudad": "Colina",
        "nom_ciudad": "Colina",
        "cod_region": "13",
        "nom_region": "Metropolitana de Santiago",
    },
    "13302": {
        "nombre":     "Lampa",
        "cod_ciudad": "Lampa",
        "nom_ciudad": "Lampa",
        "cod_region": "13",
        "nom_region": "Metropolitana de Santiago",
    },
    "13303": {
        "nombre":     "Tiltil",
        "cod_ciudad": "TilTil",
        "nom_ciudad": "Til Til",
        "cod_region": "13",
        "nom_region": "Metropolitana de Santiago",
    },
    "13401": {
        "nombre":     "San Bernardo",
        "cod_ciudad": "SanBernardo",
        "nom_ciudad": "San Bernardo",
        "cod_region": "13",
        "nom_region": "Metropolitana de Santiago",
    },
    "13402": {
        "nombre":     "Buin",
        "cod_ciudad": "Buin",
        "nom_ciudad": "Buin",
        "cod_region": "13",
        "nom_region": "Metropolitana de Santiago",
    },
    "13403": {
        "nombre":     "Calera De Tango",
        "cod_ciudad": "CaleraDeTango",
        "nom_ciudad": "Calera De Tango",
        "cod_region": "13",
        "nom_region": "Metropolitana de Santiago",
    },
    "13404": {
        "nombre":     "Paine",
        "cod_ciudad": "Paine",
        "nom_ciudad": "Paine",
        "cod_region": "13",
        "nom_region": "Metropolitana de Santiago",
    },
    "13501": {
        "nombre":     "Melipilla",
        "cod_ciudad": "Melipilla",
        "nom_ciudad": "Melipilla",
        "cod_region": "13",
        "nom_region": "Metropolitana de Santiago",
    },
    "13502": {
        "nombre":     "Alhue",
        "cod_ciudad": "Alhue",
        "nom_ciudad": "Alhue",
        "cod_region": "13",
        "nom_region": "Metropolitana de Santiago",
    },
    "13503": {
        "nombre":     "Curacavi",
        "cod_ciudad": "Curacavi",
        "nom_ciudad": "Curacavi",
        "cod_region": "13",
        "nom_region": "Metropolitana de Santiago",
    },
    "13504": {
        "nombre":     "Maria Pinto",
        "cod_ciudad": "MariaPinto",
        "nom_ciudad": "María Pinto",
        "cod_region": "13",
        "nom_region": "Metropolitana de Santiago",
    },
    "13505": {
        "nombre":     "San Pedro",
        "cod_ciudad": "SanPedro",
        "nom_ciudad": "San Pedro",
        "cod_region": "13",
        "nom_region": "Metropolitana de Santiago",
    },
    "13601": {
        "nombre":     "Talagante",
        "cod_ciudad": "Talagante",
        "nom_ciudad": "Talagante",
        "cod_region": "13",
        "nom_region": "Metropolitana de Santiago",
    },
    "13602": {
        "nombre":     "El Monte",
        "cod_ciudad": "ElMonte",
        "nom_ciudad": "El Monte",
        "cod_region": "13",
        "nom_region": "Metropolitana de Santiago",
    },
    "13603": {
        "nombre":     "Isla De Maipo",
        "cod_ciudad": "IslaDeMaipo",
        "nom_ciudad": "Isla De Maipo",
        "cod_region": "13",
        "nom_region": "Metropolitana de Santiago",
    },
    "13604": {
        "nombre":     "Padre Hurtado",
        "cod_ciudad": "PadreHurtado",
        "nom_ciudad": "Padre Hurtado",
        "cod_region": "13",
        "nom_region": "Metropolitana de Santiago",
    },
    "13605": {
        "nombre":     "Peñaflor",
        "cod_ciudad": "Peñaflor",
        "nom_ciudad": "Peñaflor",
        "cod_region": "13",
        "nom_region": "Metropolitana de Santiago",
    },
    "15101": {
        "nombre":     "Arica",
        "cod_ciudad": "Arica",
        "nom_ciudad": "Arica",
        "cod_region": "15",
        "nom_region": "Arica y Parinacota",
    },
    "99999": {
        "nombre":     "Fuera Del Territorio Nacional",
        "cod_ciudad": "",
        "nom_ciudad": "",
        "cod_region": "13",
        "nom_region": "Metropolitana de Santiago",
    },
}
